## Loan Data Cleaning & Preparation with NumPy

### Project Overview

This project focuses on cleaning, preprocessing, and preparing a real-world loan dataset from the LendingClub platform using primarily **NumPy** operations and functionalities. The objective is to demonstrate strong proficiency in low-level data manipulation techniques without relying heavily on higher-level libraries such as pandas.

The primary goal of this stage of the project is to transform raw and incomplete financial data into a structured and machine-learning-ready dataset that can later be used for predictive modeling and risk analysis tasks.

Through this workflow, the project showcases:

- Efficient numerical data handling with NumPy
- Detection and treatment of missing values
- Data type management
- Preparation of structured arrays for downstream ML applications

### Importing the Packages

In [111]:
import numpy as np

In [112]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

### Importing the Data

The LendingClub dataset is imported from a CSV file using NumPy’s `genfromtxt()` function.

The dataset is then loaded into a NumPy array for preprocessing.

In [113]:
raw_data_np = np.genfromtxt("loan-data.csv",
                            delimiter = ";", 
                            skip_header = 1, 
                            autostrip = True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]],
      shape=(10000, 14))

### Checking for Incomplete Data

Missing values are identified using NumPy’s `isnan()` function to evaluate the completeness of the dataset.

In [114]:
np.isnan(raw_data_np).sum()

np.int64(88005)

Temporary statistical values are also created:

- A temporary fill value based on the dataset maximum
- Column means calculated while ignoring missing values

In [115]:
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np, axis=0)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_10500\2996838478.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis=0)


In [116]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

The runtime warning generated during the calculation indicates that some columns contain non-numerical (string) data.

In [192]:
temporary_stats = np.array([np.nanmin(raw_data_np, axis=0),
                            temporary_mean,
                            np.nanmax(raw_data_np, axis=0)])

C:\Users\Usuario\AppData\Local\Temp\ipykernel_10500\902197374.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis=0),
C:\Users\Usuario\AppData\Local\Temp\ipykernel_10500\902197374.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis=0)])


In [193]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

### Splitting the Dataset

#### Splitting the Columns

To simplify the preprocessing workflow, we separate the dataset into:

- Columns containing string (categorical) data
- Columns containing numerical data

This separation is performed by identifying which columns produced `NaN` values when calculating the column means. Columns with `NaN` means correspond to non-numerical features, while the remaining columns are classified as numerical.

In [117]:
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [118]:
columns_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

#### Re-importing the Dataset

After identifying the column types, the dataset is imported again in two separate NumPy arrays:

- `loan_data_strings` → contains all categorical/string variables
- `loan_data_numeric` → contains all numerical variables

In [119]:
loan_data_strings = np.genfromtxt("loan-data.csv", 
                                  delimiter = ";", 
                                  skip_header = 1, 
                                  autostrip = True, 
                                  usecols = columns_strings, 
                                  dtype = str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

For the numerical dataset, missing values are temporarily replaced using the previously defined fill value.

In [120]:
loan_data_numeric = np.genfromtxt("loan-data.csv", 
                                  delimiter = ";", 
                                  skip_header = 1, 
                                  autostrip = True, 
                                  usecols = columns_numeric, 
                                  filling_values = temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]],
      shape=(10000, 6))

#### Column Names

The column headers are extracted separately from the dataset to preserve feature names during the preprocessing workflow.

After importing the full header row, the column names are split into:

- `header_strings` → headers corresponding to categorical variables
- `header_numeric` → headers corresponding to numerical variables

In [121]:
header_full = np.genfromtxt("loan-data.csv", 
                                  delimiter = ";", 
                                  autostrip = True,
                                  skip_footer = raw_data_np.shape[0],
                                  dtype = str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [122]:
header_strings, header_numeric = header_full[columns_strings], header_full[columns_numeric]

In [123]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [124]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Checkpoint Function

A custom checkpoint function is created to save intermediate preprocessing results.

The function stores:

- The dataset headers
- The processed data arrays

using NumPy’s `.npz` format.

In [125]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return checkpoint_variable

In [126]:
checkpoint_test = checkpoint("checkpoint-test", header_strings, loan_data_strings)

In [127]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Manipulating String Columns

In [128]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

The `issue_d` column is renamed to `issue_date` to create a clearer and more descriptive feature name.

In [129]:
header_strings[0] = "issue_date"

In [130]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

#### Issue Date

The `issue_date` column initially contains month and year information in string format (e.g. `"Jan-15"`).

To standardize the data:

- The year suffix (`"-15"`) is removed
- Month abbreviations are isolated
- Each month is converted into its corresponding numerical representation

For example:

- `Jan` → 1
- `Feb` → 2
- `Dec` → 12

Missing values are temporarily represented as 0.

In [131]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [132]:
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0], "-15")

C:\Users\Usuario\AppData\Local\Temp\ipykernel_10500\638482124.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0], "-15")


In [133]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [134]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [135]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                      str(i),
                                      loan_data_strings[:,0])

In [136]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

#### Loan Status

In [137]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

The `loan_status` column contains multiple categorical labels describing the repayment condition of each loan.

To simplify the feature for future predictive modeling, the statuses are converted into a binary classification variable:

- `0` → loans considered high risk or unfavorable
- `1` → loans considered acceptable or performing normally

Statuses such as:

- Charged Off
- Default
- Late (31-120 days)

along with missing values, are grouped into the high-risk category.

In [138]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [139]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [140]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], status_bad), 0, 1) 

In [141]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

#### Term

In [142]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

The `term` column contains the loan duration expressed as strings (e.g. `"36 months"` or `"60 months"`).

To standardize the feature:

- The text `" months"` is removed
- The remaining values are kept as numerical strings
- Missing values are replaced with `"60"` (worst-case scenario) as a temporary assumption based on the available categories in the dataset

In [143]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [144]:
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2], " months")
loan_data_strings[:,2]

C:\Users\Usuario\AppData\Local\Temp\ipykernel_10500\2349577218.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2], " months")


array(['36', '36', '36', ..., '36', '36', '36'], shape=(10000,), dtype='<U69')

The column name is also updated from `term` to `term_months` to better reflect the information stored in the feature.

In [145]:
header_strings[2] = "term_months"

In [146]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',
                                  '60',
                                  loan_data_strings[:,2])

After cleaning, the column contains only the standardized values:

- `36`
- `60`

making it easier to process in later analytical and modeling stages.

In [147]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

#### Grade & Sub Grade

The dataset contains both `grade` and `sub_grade` variables, which represent the credit quality assigned to each loan.

Since `sub_grade` provides a more detailed classification, we will prioritize it during preprocessing.

In [148]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [149]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [150]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

##### Filling Sub Grade

Some observations contain a missing `sub_grade` value while still having an associated `grade`.

To preserve information:

- Missing sub-grades are filled using the corresponding grade category
- The lowest sub-grade within each grade group (e.g. A5, B5) is assigned as a placeholder value

In [151]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                      i + '5',
                                      loan_data_strings[:,4])

In [152]:
np.unique(loan_data_strings[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

A small number of observations contain missing values for both `grade` and `sub_grade`. These are temporarily assigned the category `H1` to maintain consistency and avoid null entries.

In [153]:
loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '',
                                  'H1',
                                  loan_data_strings[:,4])

In [154]:
np.unique(loan_data_strings[:,4], return_counts=True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

##### Removing Grade

After completing the `sub-grade` preprocessing, we remove the original `grade` column from the dataset, since the `sub_grade` feature already captures the same classification with greater detail.

In [155]:
loan_data_strings = np.delete(loan_data_strings, 3, axis = 1)

In [156]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], shape=(10000,), dtype='<U69')

In [157]:
header_strings = np.delete(header_strings, 3)

In [158]:
header_strings[3]

np.str_('sub_grade')

##### Converting Sub Grade

After cleaning the `sub_grade` column, the categorical labels are converted into numerical representations for easier implementation in future workflows.

A dictionary mapping is created to assign a unique integer to each sub-grade category. For example:

- `A1` → 1
- `A2` → 2
- ...
- `G5` → corresponding higher numerical values

In [159]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, values))

In [160]:
dict_sub_grade

{np.str_('A1'): 1,
 np.str_('A2'): 2,
 np.str_('A3'): 3,
 np.str_('A4'): 4,
 np.str_('A5'): 5,
 np.str_('B1'): 6,
 np.str_('B2'): 7,
 np.str_('B3'): 8,
 np.str_('B4'): 9,
 np.str_('B5'): 10,
 np.str_('C1'): 11,
 np.str_('C2'): 12,
 np.str_('C3'): 13,
 np.str_('C4'): 14,
 np.str_('C5'): 15,
 np.str_('D1'): 16,
 np.str_('D2'): 17,
 np.str_('D3'): 18,
 np.str_('D4'): 19,
 np.str_('D5'): 20,
 np.str_('E1'): 21,
 np.str_('E2'): 22,
 np.str_('E3'): 23,
 np.str_('E4'): 24,
 np.str_('E5'): 25,
 np.str_('F1'): 26,
 np.str_('F2'): 27,
 np.str_('F3'): 28,
 np.str_('F4'): 29,
 np.str_('F5'): 30,
 np.str_('G1'): 31,
 np.str_('G2'): 32,
 np.str_('G3'): 33,
 np.str_('G4'): 34,
 np.str_('G5'): 35,
 np.str_('H1'): 36}

In [161]:
for key in dict_sub_grade:
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == key,
                                      str(dict_sub_grade[key]),
                                      loan_data_strings[:,3])
loan_data_strings[:,3] = loan_data_strings[:,3].astype(int)

In [162]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

#### Verification Status

The `verification_status` column contains information about whether a borrower’s financial information was verified during the loan approval process.

To simplify the feature, we convert it into a binary variable:

- `0` → not verified or missing information
- `1` → verified information

Missing values and the `Not Verified` category are grouped together, while `Verified` and `Source Verified` are treated as verified cases.

In [163]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [164]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [165]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4] == 'Not Verified'), 0, 1)

In [166]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

#### URL

The `url` column contains a full LendingClub loan URL for each observation.

Since the URL mainly stores the loan identification number, the unnecessary text portion of the link is removed, leaving only the numerical loan ID.

In [167]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'],
      shape=(10000,), dtype='<U69')

In [168]:
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
loan_data_strings[:,5]

C:\Users\Usuario\AppData\Local\Temp\ipykernel_10500\2117533971.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')


array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
      shape=(10000,), dtype='<U69')

In [169]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [170]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.], shape=(10000,))

After comparing the extracted IDs with the existing `id` column from the numerical dataset, both columns are confirmed to contain identical information.

Because the feature is redundant, we remove the `url` column from the dataset to avoid duplicated data.

In [171]:
np.array_equal(loan_data_numeric[:,0].astype(dtype=np.int32), loan_data_strings[:,5].astype(dtype=np.int32))

True

In [172]:
loan_data_strings = np.delete(loan_data_strings, 5, axis = 1)
header_strings = np.delete(header_strings, 5)

In [173]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], shape=(10000,), dtype='<U69')

In [174]:
header_strings[5]

np.str_('addr_state')

#### State Address

The `addr_state` column is renamed to `state_address` for improved readability and consistency.

An initial frequency analysis is performed to evaluate the distribution of loans across U.S. states and identify missing values.

header_strings

In [175]:
header_strings[5] = "state_address"

In [176]:
np.unique(loan_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [177]:
states_names, states_count = np.unique(loan_data_strings[:,5], return_counts = True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'TN', 'CT', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DC', 'DE', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

To reduce categorical complexity and create a more compact feature, we group individual states into broader U.S. geographic regions based on U.S. Census classifications.
https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

The regions are encoded numerically as:

- `1` → West
- `2` → South
- `3` → Midwest
- `4` → East
- `0` → missing values

In [178]:
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '',
                                  str(0),
                                  loan_data_strings[:,5])

In [179]:
states_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK'])
states_south = np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC'])
states_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH'])
states_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI'])

In [180]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_west), str(1), loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_south), str(2), loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_midwest), str(3), loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_east), str(4), loan_data_strings[:,5])

In [181]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

### Converting to Numbers

After completing the preprocessing of all categorical variables, the string dataset is converted into integer format to ensure that all features are stored numerically and are ready for future analytical applications.

In [182]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], shape=(10000, 6), dtype='<U69')

In [183]:
loan_data_strings = loan_data_strings.astype(np.int32)

#### Checkpoint 1: Strings

A checkpoint is created to save the fully processed categorical dataset along with its corresponding headers.

In [184]:
checkpoint_strings = checkpoint("checkpoint-strings", header_strings, loan_data_strings)

In [185]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [186]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], shape=(10000, 6), dtype=int32)

### Manipulating Numeric Columns

After separating the numerical variables, missing values represented by the temporary fill placeholder are identified and replaced using column-specific statistical values.

In [187]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]],
      shape=(10000, 6))

#### Substitute "Filler" Values

In [188]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

##### ID

In [189]:
temporary_fill

np.float64(68616520.0)

In [190]:
np.isin(loan_data_numeric[:,0], temporary_fill).sum()

np.int64(0)

##### Temporary Stats

We review the basic descriptive statistics generated for the numerical columns, including:

- Minimum values
- Mean values
- Maximum values

These statistics are used as reference points when replacing temporary placeholder values introduced earlier.

In [195]:
temporary_stats[:, columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

Different replacement strategies are applied depending on the feature:

- Missing values in `funded_amnt` are replaced using the column minimum value
- Missing values in:
  - `loan_amnt`
  - `int_rate`
  - `installment`
  - `total_pymnt`

are replaced using their corresponding maximum values

##### Funded Amount

In [196]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.], shape=(10000,))

In [197]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill,
                                  temporary_stats[0, columns_numeric[2]],
                                  loan_data_numeric[:,2])

##### Loaned Amount, Interest Rate, Total Payment, Installment

In [198]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [199]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill,
                                      temporary_stats[2, columns_numeric[i]],
                                      loan_data_numeric[:,i])

In [200]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]],
      shape=(10000, 6))

#### Checkpoint 2: Numeric

##### Exchange Rate

To prepare the dataset for currency standardization, historical EUR/USD exchange rate data is imported from our CSV file.

Only the adjusted closing price column is used, since it contains the relevant monthly exchange rate values required for the conversion process.

In [205]:
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ",", autostrip=True, skip_header=1, usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

The previously cleaned `issue_date` column is used to associate each loan with its corresponding monthly EUR/USD exchange rate.

For each observation:

- The loan issue month is matched to the appropriate exchange rate
- Missing issue dates are replaced using the average exchange rate value

In [206]:
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12], shape=(10000,), dtype=int32)

In [207]:
exchange_rate = loan_data_strings[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)

exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09], shape=(10000,))

The exchange rate values are reshaped and appended to the numerical dataset as a new column named `exchange_rate`.

In [208]:
loan_data_numeric.shape

(10000, 6)

In [209]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [211]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [213]:
header_numeric = np.concatenate((header_numeric, np.array(["exchange_rate"])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

##### From USD to EUR

Several financial variables in the dataset are originally expressed in U.S. dollars.

Using the previously added `exchange_rate` feature, the following columns are converted from USD to EUR:

- `loan_amnt`
- `funded_amnt`
- `installment`
- `total_pymnt`

The conversion is performed by dividing each value by its corresponding monthly exchange rate.

The converted variables are then appended to the numerical dataset as additional columns, allowing both the original USD values and standardized EUR values to remain available for future analysis.

In [214]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [215]:
columns_dollar = np.array([1,2,4,5])

In [216]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09], shape=(10000,))

In [217]:
for i in columns_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))

In [218]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]],
      shape=(10000, 11))

##### Expanding the Header

After creating the EUR-denominated financial variables, new column names are generated and added to the numerical dataset headers.

The converted features are labeled using the `_EUR` suffix, while the original currency-based variables are renamed with the `_USD` suffix to clearly distinguish between both versions.

In [220]:
header_additional = np.array([column_name + "_EUR" for column_name in header_numeric[columns_dollar]])

In [221]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [222]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [223]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [224]:
header_numeric[columns_dollar] = np.array([column_name + "_USD" for column_name in header_numeric[columns_dollar]])

In [225]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

The numerical dataset and its corresponding headers are then reorganized into a more structured column order.

In [226]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [228]:
header_numeric = header_numeric[columns_index_order]

In [229]:
loan_data_numeric = loan_data_numeric[:, columns_index_order]

In [230]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]],
      shape=(10000, 11))

#### Interest Rate

The `int_rate` feature is converted from percentage format into decimal format by dividing all values by 100.

In [231]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [232]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99], shape=(10000,))

In [233]:
loan_data_numeric[:,5] = loan_data_numeric[:,5] / 100

In [234]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29], shape=(10000,))

#### Checkpoint 2: Numeric

A second checkpoint is created to save the fully processed numerical dataset together with its corresponding headers.

In [235]:
checkpoint_numeric = checkpoint("checkpoint-numeric", header_numeric, loan_data_numeric)

In [236]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]],
       shape=(10000, 11)))

### Completing the Dataset

After preprocessing both categorical and numerical features separately, we merge the two datasets into a single consolidated array.

The corresponding headers are also combined to create the final structured dataset.

In [237]:
checkpoint_strings['data'].shape

(10000, 6)

In [238]:
checkpoint_numeric['data'].shape

(10000, 11)

In [240]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [241]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]],
      shape=(10000, 17))

In [243]:
np.isnan(loan_data).sum()

np.int64(0)

In [245]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

#### Sorting the New Dataset

We sort the completed dataset by the loan `id` column to maintain a consistent and organized record order.

In [246]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [247]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]],
      shape=(10000, 17))

#### Storing the New Dataset

Finally, the fully cleaned and transformed dataset is exported as a CSV file named:

`loan-data-preprocessed.csv`

This file contains all processed features in a machine-learning-ready format and represents the final output of the preprocessing pipeline.

In [249]:
loan_data = np.vstack((header_full, loan_data))

In [250]:
np.savetxt("loan-data-preprocessed.csv",
           loan_data,
           fmt = "%s",
           delimiter = ",")